extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern u8 castle_grounds_dl_ci4_sophie_sandstone_ci4[];
extern u8 castle_grounds_dl_ci4_sophie_sandstone_pal_rgba16[];
extern Vtx castle_grounds_dl_Cone_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Cone_mesh_layer_1_vtx_0[64];
extern Gfx castle_grounds_dl_Cone_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Cube_mesh_layer_1_vtx_0[112];
extern Gfx castle_grounds_dl_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_castle_grounds_dl_sand[];
extern Gfx mat_revert_castle_grounds_dl_sand[];
extern Gfx castle_grounds_dl_Cone_mesh_layer_1[];
extern Gfx castle_grounds_dl_Cube_mesh_layer_1[];
