extern const GeoLayout bits_area_1_geo[];
extern const GeoLayout bits_dl_B_geo[];
extern const GeoLayout bits_dl_C_geo[];
extern const GeoLayout bits_area_1[];
extern const Collision bits_area_1_collision[];
extern const u8 bits_area_1_collision_rooms[];
extern const MacroObject bits_area_1_macro_objs[];
extern Lights1 bits_dl_instant_warp_lights;
extern Lights1 bits_dl_sand_dark_lights;
extern Lights1 bits_dl_cannon_lights;
extern u8 bits_dl_ci4_sophie_sandstone_ci4[];
extern u8 bits_dl_ci4_sophie_sandstone_pal_rgba16[];
extern Vtx bits_dl_Cone_001_mesh_layer_1_vtx_cull[8];
extern Vtx bits_dl_Cone_001_mesh_layer_1_vtx_0[24];
extern Gfx bits_dl_Cone_001_mesh_layer_1_tri_0[];
extern Vtx bits_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx bits_dl_Cube_mesh_layer_1_vtx_0[136];
extern Gfx bits_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx bits_dl_Cube_mesh_layer_1_vtx_1[9];
extern Gfx bits_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx bits_dl_Cube_001_mesh_layer_1_vtx_cull[8];
extern Vtx bits_dl_Cube_001_mesh_layer_1_vtx_0[69];
extern Gfx bits_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx bits_dl_cannon_mesh_layer_1_vtx_cull[8];
extern Vtx bits_dl_cannon_mesh_layer_1_vtx_0[108];
extern Gfx bits_dl_cannon_mesh_layer_1_tri_0[];
extern Vtx bits_dl_Cone_mesh_layer_1_vtx_cull[8];
extern Vtx bits_dl_Cone_mesh_layer_1_vtx_0[40];
extern Gfx bits_dl_Cone_mesh_layer_1_tri_0[];
extern Vtx bits_dl_Cube_003_mesh_layer_1_vtx_cull[8];
extern Vtx bits_dl_Cube_003_mesh_layer_1_vtx_0[124];
extern Gfx bits_dl_Cube_003_mesh_layer_1_tri_0[];
extern Vtx bits_dl_Cube_003_mesh_layer_1_vtx_1[30];
extern Gfx bits_dl_Cube_003_mesh_layer_1_tri_1[];
extern Gfx mat_bits_dl_sand_001[];
extern Gfx mat_revert_bits_dl_sand_001[];
extern Gfx mat_bits_dl_sand[];
extern Gfx mat_revert_bits_dl_sand[];
extern Gfx mat_bits_dl_instant_warp[];
extern Gfx mat_bits_dl_sand_dark[];
extern Gfx mat_revert_bits_dl_sand_dark[];
extern Gfx mat_bits_dl_cannon[];
extern Gfx mat_bits_dl_sand_normal_speed[];
extern Gfx mat_revert_bits_dl_sand_normal_speed[];
extern Gfx bits_dl_Cone_001_mesh_layer_1[];
extern Gfx bits_dl_Cube_mesh_layer_1[];
extern Gfx bits_dl_Cube_001_mesh_layer_1[];
extern Gfx bits_dl_cannon_mesh_layer_1[];
extern Gfx bits_dl_Cone_mesh_layer_1[];
extern Gfx bits_dl_Cube_003_mesh_layer_1[];
