extern const GeoLayout castle_inside_area_1_geo[];
extern const GeoLayout castle_inside_area_1[];
extern const Collision castle_inside_area_1_collision[];
extern const MacroObject castle_inside_area_1_macro_objs[];
extern Lights1 castle_inside_dl_hurt_floor_lights;
extern u8 castle_inside_dl_PinkWall_ci4[];
extern u8 castle_inside_dl_PinkWall_pal_rgba16[];
extern u8 castle_inside_dl_blue_bricks64_ci4[];
extern u8 castle_inside_dl_blue_bricks64_pal_rgba16[];
extern u8 castle_inside_dl_blue_carpet_small_ci4[];
extern u8 castle_inside_dl_blue_carpet_small_pal_rgba16[];
extern u8 castle_inside_dl_Carpet_ON_Wood_1_ci8[];
extern u8 castle_inside_dl_Carpet_ON_Wood_1_pal_rgba16[];
extern Vtx castle_inside_dl_Cube_001_mesh_layer_1_vtx_cull[8];
extern Vtx castle_inside_dl_Cube_001_mesh_layer_1_vtx_0[186];
extern Gfx castle_inside_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx castle_inside_dl_Cube_001_mesh_layer_1_vtx_1[28];
extern Gfx castle_inside_dl_Cube_001_mesh_layer_1_tri_1[];
extern Vtx castle_inside_dl_Cube_001_mesh_layer_1_vtx_2[42];
extern Gfx castle_inside_dl_Cube_001_mesh_layer_1_tri_2[];
extern Vtx castle_inside_dl_Cube_001_mesh_layer_1_vtx_3[39];
extern Gfx castle_inside_dl_Cube_001_mesh_layer_1_tri_3[];
extern Vtx castle_inside_dl_Cube_002_mesh_layer_1_vtx_cull[8];
extern Vtx castle_inside_dl_Cube_002_mesh_layer_1_vtx_0[96];
extern Gfx castle_inside_dl_Cube_002_mesh_layer_1_tri_0[];
extern Vtx castle_inside_dl_death_plane_mesh_layer_1_vtx_cull[8];
extern Vtx castle_inside_dl_death_plane_mesh_layer_1_vtx_0[4];
extern Gfx castle_inside_dl_death_plane_mesh_layer_1_tri_0[];
extern Gfx mat_castle_inside_dl_outside[];
extern Gfx mat_revert_castle_inside_dl_outside[];
extern Gfx mat_castle_inside_dl_blue_bricks[];
extern Gfx mat_revert_castle_inside_dl_blue_bricks[];
extern Gfx mat_castle_inside_dl_floor[];
extern Gfx mat_revert_castle_inside_dl_floor[];
extern Gfx mat_castle_inside_dl_slide[];
extern Gfx mat_revert_castle_inside_dl_slide[];
extern Gfx mat_castle_inside_dl_hurt_floor[];
extern Gfx castle_inside_dl_Cube_001_mesh_layer_1[];
extern Gfx castle_inside_dl_Cube_002_mesh_layer_1[];
extern Gfx castle_inside_dl_death_plane_mesh_layer_1[];
