extern const GeoLayout castle_inside_area_1_geo[];
extern const GeoLayout castle_inside_area_1[];
extern const Collision castle_inside_area_1_collision[];
extern const MacroObject castle_inside_area_1_macro_objs[];
extern Lights1 castle_inside_dl_sm64_material_001_lights;
extern Lights1 castle_inside_dl_slide_lights;
extern Lights1 castle_inside_dl_hurt_floor_lights;
extern Vtx castle_inside_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx castle_inside_dl_Cube_mesh_layer_1_vtx_0[4];
extern Gfx castle_inside_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx castle_inside_dl_Cube_mesh_layer_1_vtx_1[8];
extern Gfx castle_inside_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx castle_inside_dl_Cube_001_mesh_layer_1_vtx_cull[8];
extern Vtx castle_inside_dl_Cube_001_mesh_layer_1_vtx_0[102];
extern Gfx castle_inside_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx castle_inside_dl_Cube_002_mesh_layer_1_vtx_cull[8];
extern Vtx castle_inside_dl_Cube_002_mesh_layer_1_vtx_0[48];
extern Gfx castle_inside_dl_Cube_002_mesh_layer_1_tri_0[];
extern Vtx castle_inside_dl_death_plane_mesh_layer_1_vtx_cull[8];
extern Vtx castle_inside_dl_death_plane_mesh_layer_1_vtx_0[4];
extern Gfx castle_inside_dl_death_plane_mesh_layer_1_tri_0[];
extern Gfx mat_castle_inside_dl_sm64_material_001[];
extern Gfx mat_castle_inside_dl_slide[];
extern Gfx mat_castle_inside_dl_hurt_floor[];
extern Gfx castle_inside_dl_Cube_mesh_layer_1[];
extern Gfx castle_inside_dl_Cube_001_mesh_layer_1[];
extern Gfx castle_inside_dl_Cube_002_mesh_layer_1[];
extern Gfx castle_inside_dl_death_plane_mesh_layer_1[];
